system: ad
K: 10
alpha: 0.1
beta: 1.0
config: null
data_dir: /data/root/GHL/RC-Flow/RC-Flow-yjy/song liu/data
diffusion_exp: 0.9
diffusion_g_end: 0.02
diffusion_g_start: 0.0001
diffusion_net_channels: 128
diffusion_net_layer: 3
diffusion_num_steps: 10
diffusion_t_end: 0.999
diffusion_t_start: 0.001
dihedral: dihedral_traj0.npy
ema_rate: 0.999
embeding_type: both
hidden_dim_nf: 256
lag1: 1
lag2: 10
latent_dim: 4
log_dir: workdir
lr: 0.001
lr_scheduler_gamma: 0.1
lr_scheduler_step_size: 10
n_epochs_SOC: 10
n_epochs_embedding: 10
n_epochs_joint: 20
n_epochs_latent: 10
num_layers_nf: 12
prior1_type: GMM
prior2_type: GMM
restart_dir: null
run_name: try
sample_stepsize: 0.01
save_feq: 50
source_struct: mdshare0_0_npt_P-H.gro
source_traj: Backbone_compact_rot+trans.xtc
sub_sample_num: 20
sub_step_num: 10
tica_data: tica_traj_ala0_d3.npy
tica_dim: 24
timesteps_embedding_dim: 32
train_batch_size: 8192
train_portion: 0.67
traj: tica_traj0.npy
use_ema: true
val_batch_size: 4096
visual_results: visual
w_decay: 0
